### ISSUE TITLE
allow regex in filter options

### ISSUE THREAD

**Issue by mirceanis** [mirceanis/stfc#3]
When filtering by device serial, it would be nice to be able to use more advanced searches using regex.

For example, the command `stfc -acf serial="(asdf|ghjk|qwer)"` should connect to the devices whose serials contain "asdf", "ghjk" or "qwer"

This would be useful for running scripts against a specific set of devices with a single `--alloc` and `--connect` command instead of an `--alloc` for each device and a final `--connect`

**Comment by JDFind** [comment]
I would also like to see this feature

**Comment by adtac** [comment]
Hey @mirceanis :)

Just saw this 1 ETH bounty on gitcoin.co. Wanna let you know I've started work on this now.

**Comment by mirceanis** [comment]
That's awesome, just remember that's testnet ETH. I wanted to get the handle of gitcoin before posting real bounties.

**Comment by adtac** [comment]
Cool, any idea on what the real bounty will be like? Almost done btw :)

**Comment by mirceanis** [comment]
I don't think I'll add another bounty for this particular one, but I think gitcoin is a great way to accelerate work like this and will probably use it more and more(for real) after this test.

That being said, I am curious to see your contribution, especially if you also find `stfc` a useful tool.

**Comment by mbeacom** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2.0 ETH (1384.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://gitcoin.ngrok.io/issue/mirceanis/stfc/3/450).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2.0 ETH (1384.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/mirceanis/stfc/3/450).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by mirceanis** [comment]
closed by PR #23
